---
title: "Get in SHP"
author: Eduardo Ramirez

editor: visual
execute:
  keep-md: true

date: "`r format(Sys.time(), '%B %d, %Y')`"
warnings: false
format:
  html:
    df-print: paged
    code-fold: true
    code-line-numbers: true
---

```{r, error = FALSE, message = FALSE, warning=FALSE}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, sf)

# links to zip files
zip_dir <- "data/zip"
wells_zip <- file.path(zip_dir, "Wells.zip")
dams_zip <- file.path(zip_dir, "Idaho_Dams.zip")
water_zip <- file.path(zip_dir, "water.zip")
shp_zip <- file.path(zip_dir, "shp.zip")
unzip(wells_zip, exdir = tempdir())
unzip(dams_zip, exdir = tempdir())
unzip(water_zip, exdir = tempdir())
unzip(shp_zip, exdir = tempdir())

# Read and filter data
wells_path <- file.path(tempdir(), "Wells.shp")
dams_path <- file.path(tempdir(), "Dam_Safety.shp")
water_path <- file.path(tempdir(), "hyd250.shp")
shp_path <- file.path(tempdir(), "County-AK-HI-Moved-USA-Map.shp")

wells <- st_read(wells_path)
dams <- st_read(dams_path)
water <- st_read(water_path)
state_shape <- st_read(shp_path) |> filter(StateName == "Idaho")
wells_filtered <- wells |> filter(Production > 5000)
dams_filtered <- dams |> filter(SurfaceAre > 50)
water_filtered <- water |> filter(FEAT_NAME %in% c("Snake River", "Henrys Fork"))
crs_idaho <- st_crs(4326)
state_shape <- st_transform(state_shape, crs_idaho)
wells_filtered <- st_transform(wells_filtered, crs_idaho)
dams_filtered <- st_transform(dams_filtered, crs_idaho)
water_filtered <- st_transform(water_filtered, crs_idaho)


```

# Map with filtered Data

This map only includes well locations with a production of more than 5000 gallons, only shows dams with a surface area larger than 50 acres, and shows the Snake and Henry's Fork rivers.

```{r, error = FALSE, message = FALSE, warning=FALSE, fig.width=10, fig.height=8}

# plot map
idaho_map <- ggplot() +
  geom_sf(data = state_shape) +
  geom_sf(data = wells_filtered, aes(color = "Wells"), size = 2) +
  geom_sf(data = dams_filtered, aes(color = "Dams"), size = 2) +
  geom_sf(data = water_filtered, aes(color = "Rivers"), size = 1) +
  scale_color_manual(values = c("Wells" = "orange", "Dams" = "darkgreen", "Rivers" = "blue"), name = "Features") +
  labs(title = "Water Systems in Idaho") +
  theme_minimal()

# Save as png
ggsave("IdahoWater.png", plot = idaho_map, width = 10, height = 8)


idaho_map
```
